# 사이트 기본 설정
title: My New Jekyll Site
email: woals6318@gmail.com
description: >- # This means to ignore newlines until "baseurl:"
  여기에 사이트에 대한 간단한 설명을 작성하세요.

# 빌드 설정
# 소스 폴더를 명시적으로 지정할 필요는 없지만,
# 혹시 모르니 다시 확인하세요.
source: /frontend
baseurl: ""
destination: _site

# GitHub Pages를 위한 설정 (필요한 경우)
github: [metadata]
plugins:
  - jekyll-feed