# Generated by Django 5.2.7 on 2025-10-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_last_activity",
            field=models.DateTimeField(auto_now=True, verbose_name="최종 활동 시각"),
        ),
    ]
