# Generated by Django 5.2.7 on 2025-12-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_member_member_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("PROFESSOR", "교수"),
                    ("GRADUATE", "대학원생"),
                    ("UNDERGRADUATE", "학부생/졸업생"),
                ],
                default="UNDERGRADUATE",
                max_length=20,
                verbose_name="신분",
            ),
        ),
    ]
