# Generated by Django 5.2.9 on 2025-12-25 03:59

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("members", "0003_member_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["sid"]},
        ),
        migrations.AddField(
            model_name="member",
            name="username",
            field=models.CharField(
                default="",
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="member",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="member_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="join_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="member_last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="member_user_permissions", to="auth.permission"
            ),
        ),
    ]
